services:
  test-db:
    image: postgres:15
    container_name: employee_directory_test_db
    environment:
      POSTGRES_DB: test_employee_directory
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - ./database/init/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/init/02-seed-data-test.sql:/docker-entrypoint-initdb.d/02-seed-data.sql
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_employee_directory"]
      interval: 5s
      timeout: 5s
      retries: 5